# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'GoogleServicesUnwrap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for GoogleServicesUnwrap
  pod 'Firebase', '7.11.0'
end
